Webscraping with Beautifulsoup
CSEdgeOfficial/learn.csedge.courses pull request #407
Opened 2024-06-05 10:31 UTC by vaishali-sharma-20

Uploading blogs on Web Scraping with Beautifulsoup.

## Related Issue
Issue: #399

## Description
This task is assigned to me for technical writing of web scraping with Beautifulsoup using Python.
I have created two files as
1. Step-by-step guide for Web Scraping
2. Example
 I have saved these files in a new folder named Web Scraping with Beautiful soup.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
I will upload images that I used in blogs.

2024-06-05 15:24 UTC, CSEdgeOff requested changes
Even the Titles are changed 
Make proper changes and add a Banner images and also make sure of SEO

2024-06-06 11:19 UTC, vaishali-sharma-20 reviewed
Image updated.  Let me know if any more changes are needed.

2024-06-06 11:41 UTC, Durgesh-Vaigandla commented on posts/Web Scraping tool with BeautifulSoup/WebScrapingWithBeautifulSoup.html
Title was not correct

2024-06-06 11:41 UTC, Durgesh-Vaigandla commented on posts/Web Scraping tool with BeautifulSoup/ExampleOfBuildingWebScrapingApplication.html
Title was not correct

2024-06-06 11:57 UTC, vaishali-sharma-20 commented on posts/Web Scraping tool with BeautifulSoup/ExampleOfBuildingWebScrapingApplication.html
Please check it once again. I have changed the title as well as some meta data.

2024-06-08 15:24 UTC, vaishali-sharma-20 commented
Hello @Durgesh-Vaigandla and @CSEdgeOff, I have updated the title and made all the relevant changes as discussed. Could you please review the updates and let me know if everything is in order?

2024-06-09 04:16 UTC, merged

2024-06-17 04:17 UTC, Durgesh-Vaigandla commented
@vaishali-sharma-20 You Forgot to add the Images here too.